/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[Firma]
      ,[Nazwisko]
      ,[Imię]
      ,[Adres e-mail]
      ,[Tytuł zawodowy]
      ,[Telefon służbowy]
      ,[Telefon domowy]
      ,[Telefon komórkowy]
      ,[Numer faksu]
      ,[Adres]
      ,[Miasto]
      ,[Województwo]
      ,[Kod pocztowy]
      ,[Kraj/region]
      ,[Strona sieci Web]
      ,[Uwagi]
  FROM [Northwind].[dbo].[Pracownicy]